language: node_js
node_js:
- 6.10.3
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
env:
  global:
    secure: jbcfQNJrOYrWz/pO+Bz4tJYmxxIjLeUlnls60K3T7AGJvaDgpq8YYrRHLr5jx81x5qDgUr+/vT7yHOFTrTDiXK9THdeU8s8Vu45Q5/BMt7UaZrs4fugMZszK09rIBafXxo0nUA0dFUcrtbjve9MGSDVuE6HvlLJO5yTjG69Gabr+4xhPZsSMVCGmJ80CyThMOCwGyn8CA1Iv5lqZ5N8VXgf4Z0z0iGhq8OPsoMrn7ynNwNBCd3kdi5vjE9S69cWQkm0pKRnAobLbQfUGa9ZlfRMn7NnebgFN2Vr/IHrdex6Z4lxdtz79HmY86qHcyAQLZHsrOBwd6dpetyGLRfSrS13mvJkz5YVaQmo9sEqtzWexI+rsVkPoe4mqCtk3fGTpySURmbG4WLwQ6C4EGcFRek8zgKgvHtUDYAcBezqnofE5Qeg2KGcO4z00fOAv/ERuMv/xAQvouhUEXLNFll+xUIzUcIuZQ5ZltVOkPKBkG91H38mj26bPtV3HugsidimJ+VNuc87YujosH1kbVdNB6XA4dgEEeyqeVKT7gFJjtZSq31mzkqoFZWOUK03JJCmQtQTrWUWTiPUa77arBRwZk58aVTpspPS6PJ8o4zTinrj9m9VuE+1uiZUQXu4gUSB0kCzAEDe9Ab+cvOdNBpp7rhrsqds2ajTf8jdhpzna3gQ=
